// <auto-generated />
using System;
using AquaparkApplication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AquaparkApplication.Migrations
{
    [DbContext(typeof(AquaparkDbContext))]
    [Migration("20190528195016_SeedPeriodicDiscount")]
    partial class SeedPeriodicDiscount
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AquaparkApplication.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxAmountOfPeople");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<int?>("ZoneId");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Attractions");

                    b.HasData(
                        new { Id = 1, MaxAmountOfPeople = 5, Name = "Sauna 1", ZoneId = 1 },
                        new { Id = 2, MaxAmountOfPeople = 5, Name = "Sauna 2", ZoneId = 1 },
                        new { Id = 3, MaxAmountOfPeople = 5, Name = "Sauna 3", ZoneId = 1 },
                        new { Id = 4, MaxAmountOfPeople = 7, Name = "Sauna 4", ZoneId = 1 },
                        new { Id = 5, MaxAmountOfPeople = 3, Name = "Sauna 5", ZoneId = 1 },
                        new { Id = 6, MaxAmountOfPeople = 2, Name = "Sauna 6", ZoneId = 1 },
                        new { Id = 7, MaxAmountOfPeople = 8, Name = "Sauna 7", ZoneId = 1 },
                        new { Id = 8, MaxAmountOfPeople = 25, Name = "Basen 1", ZoneId = 2 },
                        new { Id = 9, MaxAmountOfPeople = 25, Name = "Basen 2", ZoneId = 2 },
                        new { Id = 10, MaxAmountOfPeople = 30, Name = "Basen 3", ZoneId = 2 },
                        new { Id = 11, MaxAmountOfPeople = 20, Name = "Basen 4", ZoneId = 2 },
                        new { Id = 12, MaxAmountOfPeople = 5, Name = "Spa 1", ZoneId = 3 },
                        new { Id = 13, MaxAmountOfPeople = 5, Name = "Spa 2", ZoneId = 3 },
                        new { Id = 14, MaxAmountOfPeople = 10, Name = "Spa 3", ZoneId = 3 }
                    );
                });

            modelBuilder.Entity("AquaparkApplication.Models.AttractionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttractionId");

                    b.Property<DateTime?>("FinishTime");

                    b.Property<int>("PositionId");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex("PositionId");

                    b.ToTable("AttractionHistories");
                });

            modelBuilder.Entity("AquaparkApplication.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfOrder");

                    b.Property<int?>("UserDataId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserDataId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AquaparkApplication.Models.PeriodicDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FinishTime");

                    b.Property<DateTime>("StartTime");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.ToTable("PeriodicDiscounts");

                    b.HasData(
                        new { Id = 1, FinishTime = new DateTime(2019, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), StartTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Value = 0.80m }
                    );
                });

            modelBuilder.Entity("AquaparkApplication.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CanBeUsed");

                    b.Property<int?>("OrderId");

                    b.Property<int?>("PeriodicDiscountId");

                    b.Property<int?>("SocialClassDiscountId");

                    b.Property<int?>("TicketId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PeriodicDiscountId");

                    b.HasIndex("SocialClassDiscountId");

                    b.HasIndex("TicketId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("AquaparkApplication.Models.SocialClassDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SocialClassName")
                        .HasMaxLength(30);

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.ToTable("SocialClassDiscounts");
                });

            modelBuilder.Entity("AquaparkApplication.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Days");

                    b.Property<double>("EndHour");

                    b.Property<int>("Months");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("PeriodicDiscountId");

                    b.Property<decimal>("Price");

                    b.Property<double>("StartHour");

                    b.Property<int?>("ZoneId");

                    b.HasKey("Id");

                    b.HasIndex("PeriodicDiscountId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("AquaparkApplication.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(30);

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .HasMaxLength(40);

                    b.Property<string>("Surname")
                        .HasMaxLength(30);

                    b.Property<Guid>("UserGuid");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AquaparkApplication.Models.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<string>("Surname")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("UsersData");
                });

            modelBuilder.Entity("AquaparkApplication.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxAmountOfPeople");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new { Id = 1, MaxAmountOfPeople = 35, Name = "Strefa saun" },
                        new { Id = 2, MaxAmountOfPeople = 100, Name = "Strefa basenów" },
                        new { Id = 3, MaxAmountOfPeople = 20, Name = "Strefa spa" }
                    );
                });

            modelBuilder.Entity("AquaparkApplication.Models.ZoneHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("FinishTime");

                    b.Property<int>("PositionId");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("ZoneId");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ZoneHistories");
                });

            modelBuilder.Entity("AquaparkApplication.Models.Attraction", b =>
                {
                    b.HasOne("AquaparkApplication.Models.Zone", "Zone")
                        .WithMany("Attractions")
                        .HasForeignKey("ZoneId");
                });

            modelBuilder.Entity("AquaparkApplication.Models.AttractionHistory", b =>
                {
                    b.HasOne("AquaparkApplication.Models.Attraction", "Attraction")
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AquaparkApplication.Models.Position", "Position")
                        .WithMany("AttractionHistories")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AquaparkApplication.Models.Order", b =>
                {
                    b.HasOne("AquaparkApplication.Models.UserData", "UserData")
                        .WithMany()
                        .HasForeignKey("UserDataId");

                    b.HasOne("AquaparkApplication.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AquaparkApplication.Models.Position", b =>
                {
                    b.HasOne("AquaparkApplication.Models.Order")
                        .WithMany("Positions")
                        .HasForeignKey("OrderId");

                    b.HasOne("AquaparkApplication.Models.PeriodicDiscount", "PeriodicDiscount")
                        .WithMany()
                        .HasForeignKey("PeriodicDiscountId");

                    b.HasOne("AquaparkApplication.Models.SocialClassDiscount", "SocialClassDiscount")
                        .WithMany()
                        .HasForeignKey("SocialClassDiscountId");

                    b.HasOne("AquaparkApplication.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId");
                });

            modelBuilder.Entity("AquaparkApplication.Models.Ticket", b =>
                {
                    b.HasOne("AquaparkApplication.Models.PeriodicDiscount", "PeriodicDiscount")
                        .WithMany("Tickets")
                        .HasForeignKey("PeriodicDiscountId");

                    b.HasOne("AquaparkApplication.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");
                });

            modelBuilder.Entity("AquaparkApplication.Models.ZoneHistory", b =>
                {
                    b.HasOne("AquaparkApplication.Models.Position", "Position")
                        .WithMany("ZoneHistories")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AquaparkApplication.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
